# /roles/master/tasks/main.yaml

- name: Master Tasks
  debug:
    msg: "These are master tasks"
  tags:
    - never
    - debug

- name:  Setup kubelet environment files
  command: /vagrant/scripts/extra.sh

- name: Initialize the Kubernetes cluster using kubeadm
  command: kubeadm init --apiserver-advertise-address="192.168.50.10" --apiserver-cert-extra-sans="192.168.50.10"  --node-name k8s-master --pod-network-cidr=192.168.1.0/16

- name: Create kubeconfig dir for vagrant user
  file:
    path: /home/vagrant/.kube
    state: directory
    mode: 0755

- name:  Copy config file for vagrant user
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/vagrant/.kube/config
    owner: vagrant
    group: vagrant
    remote_src: yes

- name:  Copy config file for WSL user
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /vagrant/konfig/config
    remote_src: yes

- name: Install Weave
  become: false
  shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"

- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_command

- name: Save command to file
  copy:
    content: "{{ join_command.stdout_lines[0] }}"
    dest: /tmp/join-command

- name: Copy join command to local file
  fetch:
    src: /tmp/join-command
    dest: "./join-command"
    flat: yes


- name: Download Kompose
  get_url:
    url: https://github.com/kubernetes/kompose/releases/download/v1.17.0/kompose-linux-amd64
    dest: /usr/local/bin/kompose
    mode: 0655

- name: Install Openshift
  pip:
    name: openshift
    state: latest
